#!/usr/bin/env ruby

def run(io, error_io, github_event, client)
  io.puts "SaturnCI SDK version: #{SaturnCI::VERSION}"

  return 0 unless github_event == "push"
  return 0 if ENV["DELETED"] == "true"

  branch_name = ENV["BRANCH_NAME"]
  if branch_name.to_s.empty?
    error_io.puts "BRANCH_NAME env var is required"
    return 1
  end

  commit_hash = ENV["COMMIT_HASH"]
  if commit_hash.to_s.empty?
    error_io.puts "COMMIT_HASH env var is required"
    return 1
  end

  commit_message = ENV["COMMIT_MESSAGE"]
  author_name = ENV["AUTHOR_NAME"]

  io.puts "Branch name: #{branch_name}"
  io.puts "Commit hash: #{commit_hash}"
  io.puts "Commit message: #{commit_message}"
  io.puts "Author name: #{author_name}"

  test_suite_run = SaturnCI::TestSuiteRun.create(
    client: client,
    task_adapter_name: "rspec",
    repository: "saturnci/words",
    branch_name: branch_name,
    commit_hash: commit_hash,
    commit_message: commit_message,
    author_name: author_name,
  )

  io.puts "Running test suite: #{test_suite_run.url}"
  test_suite_run.wait_for_completion
  io.puts "Tests #{test_suite_run.status.downcase}."

  0
end

def client
  SaturnCI::Client.new(credentials)
end

def credentials
  SaturnCI::Credentials.new(
    api_token: ENV.fetch("SATURNCI_API_TOKEN")
  )
end

exit run($stdout, $stderr, ENV["GITHUB_EVENT"], client) if $PROGRAM_NAME == __FILE__
