version: "3.8"

services:
  saturn_test_app:
    hostname: saturn_test_app
    image: ${SATURN_TEST_APP_IMAGE_URL}
    build:
      context: ..
      dockerfile: .saturnci/Dockerfile
    volumes:
      - ../:/app
    env_file:
      - .env
